# Generated by Django 3.2.8 on 2022-12-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_100', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listtop100',
            name='date_modify',
            field=models.CharField(max_length=100),
        ),
    ]
