# Generated by Django 3.2.8 on 2022-11-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShowCaseHome',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('thumbnail', models.CharField(max_length=300)),
                ('url', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=200)),
                ('order', models.IntegerField()),
                ('imageUrl', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
