# Generated by Django 3.2.8 on 2023-01-01 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('video', '0002_alter_videos_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('quality', models.IntegerField(default=128)),
                ('stream_url', models.CharField(max_length=300)),
                ('video_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.videos')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
