# Generated by Django 3.2.8 on 2022-12-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='type',
            field=models.CharField(default='VIDEO', max_length=100),
        ),
    ]
