# Generated by Django 3.2.8 on 2022-12-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist_detail', '0003_auto_20221213_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artists',
            name='image_url',
            field=models.CharField(default='Null', max_length=200),
        ),
        migrations.AlterField(
            model_name='artists',
            name='short_link',
            field=models.CharField(default='Null', max_length=100),
        ),
    ]
