# Generated by Django 3.2.8 on 2022-12-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist_detail', '0005_auto_20221214_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artists',
            name='image_url',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='artists',
            name='short_link',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
