# Generated by Django 3.2.8 on 2022-11-30 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopicEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('group_name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListPlaylists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('thumbnail', models.CharField(max_length=300)),
                ('duration', models.DurationField()),
                ('type', models.CharField(max_length=100)),
                ('date_modify', models.CharField(max_length=100)),
                ('topic_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topic_event_home.topicevents')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('short_link', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=200)),
                ('artist_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topic_event_home.listplaylists')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
