# Generated by Django 3.2.8 on 2022-11-30 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopicEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('groupName', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='ListPlaylists',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('thumbnail', models.CharField(max_length=300)),
                ('duration', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=100)),
                ('dateModify', models.CharField(max_length=100)),
                ('topic_eventID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topic_event_home.topicevents')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('artistId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('shortLink', models.CharField(max_length=100)),
                ('imageUrl', models.CharField(max_length=200)),
                ('artist_eventID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topic_event_home.listplaylists')),
            ],
        ),
    ]
