# Generated by Django 3.2.8 on 2022-12-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('cover_image', models.CharField(max_length=200)),
                ('thumbnail', models.CharField(max_length=300)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
